# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4e92a3e78f422e0da46dbab141ef65b16aa688bcb6bd49d30ee1d47b05d37c3c9a44ae7d8ebc8819edc598871785ecec89c6fff3b19db901cd6561e36957a48

test:
  secret_key_base: 33c29d8a86f476f8090371d5a497e4ef89e1f7caa24cbb917d04d6e6a69feb43acd95c144aa8d65a160f02e27ab0cae588e815ec1aa17f6f2b96d1b4231c47c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
